### PR TITLE
multi-targeted library+tests to include .net 5.0

### LINKED ISSUE #169: Consider multitargeting with .NET 5.0
surely its time to multi-target for .net 5.0 ? :)

_Originally posted by @f2calv in https://github.com/samsmithnz/AzurePipelinesToGitHubActionsConverter/pull/167#discussion_r541590842_

### PR DESCRIPTION
**Pull request by f2calv**
Also enabled c# 9.0

Resolves #169

### CODE REVIEW

**Comment by samsmithnz** [comment]
Two questions: 
1. Doesn't this now remove .NET Framework support? I only ask because you pushed for for a downgrade of the project from .NET Standard 2.1 to 2.0. I have no problem with this, but curious.
2. It looks like you branched from v0.12 of the main trunk, but main is up to 0.13.1. Can you merge in those changes too?

**Comment by f2calv** [comment]
Being multi-targeted means it separately targets multiple frameworks quite happily, they are packaged in separate directories in the same nupkg file. Yes sure your package doesn't *really need* targeting .NET 5.0, but it won't hurt and we like to push boundaries and .NET 5.0 is the future right? :)

It's not a breaking change the .NET Standard 2.0 package is still there, NuGet has been able to handle multi-targeted packages for a very long time now - but there is no rush to merge from me if you are concerned.

I'd like to take a closer look at the gh actions workflow next and include GitVersion to sort out #126 if you are ok with that?

**Comment by f2calv** [comment]
My first instance where GH actions behaviour seems to differ from Azure Pipelines, maybe best wait until 14th Dec for the .NET 5 to be the default - https://github.com/actions/virtual-environments/issues/1891

**Comment by samsmithnz** [comment]
It's odd that the test project is trying to build .NET **Framework** 5.x. I tried to fix it with a matrix, but ultimately ended up rolling back to your changes

**Comment by f2calv** [comment]
If you want to learn more I would strongly recommend downloading [NuGetPackageExplorer](https://github.com/NuGetPackageExplorer/NuGetPackageExplorer) and then using it to inspect the inside and compare your nupkg with other nupkg files such as;

- https://www.nuget.org/api/v2/package/CasCap.Apis.GooglePhotos/1.0.13
- https://www.nuget.org/api/v2/package/Newtonsoft.Json/12.0.3

You can then see the folder structure per target and the variety of other bells and whistles that can be enabled.

**Comment by samsmithnz** [comment]
Quick note: If you change the .NET 5 version to '5.0.x', it will get further.

Looks like there is an update tomorrow that will unblock the rest: https://github.com/actions/virtual-environments/issues/1891

**Comment by samsmithnz** [comment]
@f2calv, do you have plans to finish this? It doesn't do much for my projects. If you are done, I'd propose abandoning it.

**Pull request closed without merging**
